version: 2
updates:
- package-ecosystem: github-actions
  versioning-strategy: increase
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: ci
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  commit-message:
    prefix: fix
