options:
  prev_tag: versio-prev

projects:
- name: ed-system-search
  id: 1
  tag_prefix: ''
  labels: cargo
  version:
    file: Cargo.toml
    toml: package.version
  also:
  - file: README.md
    pattern: ed-system-search (\d+\.\d+\.\d+)
  hooks:
    post_write: cargo fetch

sizes:
  use_angular: true
  none: [ci, "-"]
