name: Build GitHub Releases
on:
  push:
    tags-ignore:
    - versio-prev
jobs:
  generate-list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      name: Checkout the repository
      with:
        lfs: true
    - uses: actions/cache@v2.1.5
      name: Cache cargo dependencies
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        path: |
          .cache
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          target
    - uses: actions-rs/toolchain@v1
      name: Install rust toolchain
      with:
        default: true
        profile: minimal
        toolchain: stable
    - uses: actions-rs/cargo@v1
      name: Build release version
      with:
        args: --release --locked
        command: build
    - run: wget -O systemsPopulated.json.gz  https://www.edsm.net/dump/systemsPopulated.json.gz
    - run: ./runners/generate-all-combinations
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Alliance-Anarchy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Alliance-Communism.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Alliance-Confederacy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Alliance-Cooperative.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Alliance-Corporate.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Alliance-Democracy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Alliance-Dictatorship.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Alliance-Feudal.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Alliance-Patronage.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Alliance-Prison.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Alliance-Prison colony.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Alliance-Theocracy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Empire-Anarchy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Empire-Communism.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Empire-Confederacy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Empire-Cooperative.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Empire-Corporate.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Empire-Democracy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Empire-Dictatorship.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Empire-Feudal.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Empire-Patronage.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Empire-Prison.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Empire-Prison colony.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Empire-Theocracy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Federation-Anarchy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Federation-Communism.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Federation-Confederacy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Federation-Cooperative.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Federation-Corporate.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Federation-Democracy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Federation-Dictatorship.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Federation-Feudal.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Federation-Patronage.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Federation-Prison.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Federation-Prison colony.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Federation-Theocracy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Independent-Anarchy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Independent-Communism.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Independent-Confederacy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Independent-Cooperative.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Independent-Corporate.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Independent-Democracy.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Independent-Dictatorship.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Independent-Feudal.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Independent-Patronage.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Independent-Prison.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Independent-Prison colony.txt
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: potential-faction-systems
        path: potential-faction-systems-Independent-Theocracy.txt
  build:
    runs-on: ${{ matrix.os }}
    steps:
    - run: ${{ matrix.install }}
      env:
        DEBIAN_FRONTEND: noninteractive
      name: Install additional dependencies
    - uses: actions/checkout@v2.3.4
      name: Checkout the repository
      with:
        lfs: true
    - uses: actions/cache@v2.1.5
      name: Cache cargo dependencies
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        path: |
          .cache
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          target
    - uses: actions-rs/toolchain@v1
      name: Install rust toolchain
      with:
        default: true
        profile: minimal
        toolchain: stable
    - uses: actions-rs/cargo@v1
      name: Build release version
      with:
        args: --release --locked
        command: build
    - id: get_repository_name
      name: Calculate repository name
      run: echo ::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk
        -F / '{print $2}' | sed -e "s/:refs//")
      shell: bash
    - uses: actions/upload-artifact@v2
      name: Store built version
      with:
        name: ${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-${{ matrix.target
          }}
        path: ./target/release/${{ steps.get_repository_name.outputs.REPOSITORY_NAME
          }}${{ matrix.suffix }}
    strategy:
      matrix:
        include:
        - os: macos-latest
          suffix: ''
          target: x86_64-apple-darwin
          install: ''
        - os: ubuntu-latest
          suffix: ''
          target: x86_64-unknown-linux-gnu
          install: ''
        - os: windows-latest
          suffix: .exe
          target: x86_64-pc-windows-msvc
          install: ''
  release:
    needs:
    - generate-list
    - build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      name: Checkout the repository
      with:
        lfs: true
        fetch-depth: 0
    - uses: actions/cache@v2.1.5
      name: Cache cargo dependencies
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        path: |
          .cache
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          target
    - uses: actions/download-artifact@v2
      name: Retrieve built binaries
    - uses: actions-rs/toolchain@v1
      name: Install rust toolchain
      with:
        default: true
        profile: minimal
        toolchain: stable
    - id: get_previous_version
      name: Calculate previous version
      run: echo ::set-output name=PREVIOUS_VERSION::$(git tag | sort --version-sort
        | tail -n 3 | head -n 1)
      shell: bash
    - uses: actions-rs/cargo@v1
      name: Install TOML Reader
      with:
        args: toml-cli
        command: install
    - id: get_repository_name
      name: Calculate repository name
      run: echo ::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk
        -F / '{print $2}' | sed -e "s/:refs//")
      shell: bash
    - id: get_version
      name: Calculate current version number
      run: echo ::set-output name=VERSION::v$(toml get Cargo.toml package.version
        | tail -c +2 | head -c -2)
      shell: bash
    - uses: dlavrenuek/conventional-changelog-action@v1.1.1
      id: changelog
      with:
        from: ${{ steps.get_previous_version.outputs.PREVIOUS_VERSION }}
        to: ${{ steps.get_version.outputs.VERSION }}
    - env:
        GITHUB_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
      id: create_release
      uses: actions/create-release@v1.1.4
      with:
        draft: false
        prerelease: false
        body: ${{ steps.changelog.outputs.body }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        tag_name: ${{ steps.get_version.outputs.VERSION }}
    - uses: actions/upload-release-asset@v1.0.2
      name: Upload x86_64-unknown-linux-gnu binaries to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-x86_64-unknown-linux-gnu/${{
          steps.get_repository_name.outputs.REPOSITORY_NAME }}
        asset_name: ${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-x86_64-unknown-linux-gnu
        asset_content_type: application/octet-stream
    - uses: actions/upload-release-asset@v1.0.2
      name: Upload x86_64-apple-darwin binaries to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-x86_64-apple-darwin/${{
          steps.get_repository_name.outputs.REPOSITORY_NAME }}
        asset_name: ${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-x86_64-apple-darwin
        asset_content_type: application/octet-stream
    - uses: actions/upload-release-asset@v1.0.2
      name: Upload x86_64-pc-windows-msvc binaries to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-x86_64-pc-windows-msvc/${{
          steps.get_repository_name.outputs.REPOSITORY_NAME }}.exe
        asset_name: ${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}-x86_64-pc-windows-msvc.exe
        asset_content_type: application/octet-stream
    - uses: alexellis/upload-assets@0.3.0
      name: Upload potential faction list
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_paths: '["./potential-faction-systems/*"]'
